export const SUCCESS_REGISTER = "SUCCESS_REGISTER";
export const ERROR_REGISTER = "ERROR_REGISTER";
export const CLEAN_ALERT = "CLEAN_ALERT";

export const USER_AUTHENTICATED = "USER_AUTHENTICATED";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const SIGNOUT = "SIGNOUT";
